### PR TITLE
Update dependencies: 🔥 Firebase 9 and Firebaseui 0.600

### PR DESCRIPTION
**Pull request by shiiinji**
- Update Firebase 9 and Firebaseui 0.600

#156

### CODE REVIEW

**Comment by mwikblom** [comment]
When will there be a release with support for firebase SDK 9? It would be greatly appreciated 🥇

**Comment by shiiinji** [comment]
This repository is just forked project for creating pull request to firebase/firebaseui-web-react.
https://github.com/firebase/firebaseui-web-react/pull/158

I hope to merge this modification, but it depends on code owner of firebase/firebaseui-web-react.

I feel, firebase/firebaseui-web-react have been inactive..
In my projects, I upgraded  Firebase 9, but firebase/firebaseui-web-react have not worked yet.

**Comment by usedf** [comment]
@shiiinji could you publish this fork to NPM? The original repository seems inactive.

**Comment by shiiinji** [comment]
@usedf 

I published this forked NPM for my personal project.
But I published it until the original to be updated.
So the npm library name is tmp-fork-react-firebaseui-v0.600.0,
if you want to use, I consider I should rename the npm library name and updated package.json, before you use.

https://www.npmjs.com/package/tmp-fork-react-firebaseui-v0.600.0

**Comment by usedf** [comment]
Yes, I would like to use it as a temporary solution until the original package is updated.

Thank you, it works well.

**Pull request merged**
